import { Footer, Navbar } from '@/components';
import './globals.css'
import { Providers } from '../redux/provider';

export const metadata = {
  title: 'Last Shop App',
  description: 'Generated by create next app to Last Shop',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className='relative'>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
