"use_client";

import { Footer, Navbar } from '@/components';
import './globals.css'
import { Providers } from './redux/provider'

export const metadata = {
  title: 'Last Shop App',
  description: 'Generated by create next app to Last Shop',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <Providers>
        <body className='relative'>
          <Navbar />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  )
}
